### ISSUE TITLE
Wrong random range

### ISSUE THREAD

**Issue by letheed** [xsellier/godot-uuid#1]
Shouldn't the randomness be `(randi() % (max_value + 1 - min_value)) + min_value` ?

**Comment by xsellier** [comment]
Indeed, I did it too quickly. I pushed a fix and updated the submitted asset on godot-asset.

**Comment by letheed** [comment]
You still need the `+1`. n % 255 ∈ [0; 254]

**Comment by xsellier** [comment]
In fact I removed the min_value (was always 0)

```
static func getRandomInt(max_value):
  randomize()

# http://docs.godotengine.org/en/stable/classes/class_@gdscript.html#class-gdscript-randi
return randi() % max_value
```

I pushed the version 1.0.2 (updating the godot asset)

**Comment by letheed** [comment]
Yeah but I'm guessing you want an 8bit integer, so in [0; 255]. But n % 255 is in [0; 254]. So you need either `getRandomInt(256)` or `randi() % (max_value  + 1)`.

**Comment by xsellier** [comment]
You are right, again,sorry I was a bit asleep this morning, I changed 255 for 256, meaning I use the correct range now.
