### ISSUE TITLE
Adapt folder structure to official recommendation

### ISSUE THREAD

**Issue by ghtyrant** [xsellier/godot-uuid#10]
Thanks a lot for your plugin!

The official documentation suggests that you put your plugin in `addons/uuid/`. Otherwise all the files of the plugin are copied to the root of a user's project when they install it. This might cause some clashes (e.g., I now have your README.md at the root of my project).

https://docs.godotengine.org/en/stable/community/asset_library/submitting_to_assetlib.html#introduction says:
> When creating non-project assets, it is common practice to place your files inside of an addons/asset_name/ folder. Do this to avoid having your files clash with other assets, or with the files of users installing your asset. This folder will not be automatically generated when a user installs your asset.

**Comment by xsellier** [comment]
Done thank you
