### ISSUE TITLE
`v4_rng` does not return deterministic results based on `RandomNumberGenerator`

### ISSUE THREAD

**Issue by tavurth** [xsellier/godot-uuid#12]
Since `randomize` is called at the start of the `v4_rng` function.

Please see this PR for a fix:

https://github.com/binogure-studio/godot-uuid/pull/11

Which allows for deterministic creation of uuid, I think this was just a bug?

```gdscript
func get_rng(item: Dictionary) -> RandomNumberGenerator:
	var rng = RandomNumberGenerator.new()
	rng.set_seed(1)
	return rng


func _init(item: Dictionary) -> void:
	# The following ID should always be the same
	self.id = preload("uuid.gd").v4_rng(get_rng(item))
```

**Comment by xsellier** [comment]
Did you run the test locally without the randomize?

**Comment by tavurth** [comment]
Sure, I've been using it in my games & apps for well over 3 years now

**Comment by tavurth** [comment]
We can write a million instance test if you really want?

**Comment by xsellier** [comment]
I'm talking aobut running those tests:
https://github.com/binogure-studio/godot-uuid/blob/master/test.gd

Also, it should NEVER return the same UUID based on the RFC, because the RFC needs a pseudo random number to generate a UUID.
https://datatracker.ietf.org/doc/html/rfc4122#section-4.4

**Comment by tavurth** [comment]
I mean more in these types of instances:

```gdscript
func test_uuid():
	var uuid = preload("res://addons/data-store/uuid.gd").new()

	var rng = RandomNumberGenerator.new()
	rng.set_seed(1)

	var first = uuid.v4_rng(rng)

	for i in range(1000000):
		rng.set_seed(1)
		assert(first != uuid.v4_rng(rng), "It was not the same")
```

But I guess that might actually be `Uuidv5`?

**Comment by xsellier** [comment]
It could be v3 or v5, based on the RFC.

**Comment by tavurth** [comment]
> Also, it should NEVER return the same UUID based on the RFC, because the RFC needs a pseudo random number to generate a UUID.
> https://datatracker.ietf.org/doc/html/rfc4122#section-4.4

<img width="742" alt="Screenshot 2023-12-16 at 21 57 35" src="https://github.com/binogure-studio/godot-uuid/assets/100964/90eb7110-e20d-43b8-9bdc-21b135de0f42">

I want determinism in this case, because based on the data I always want to generate the same UUID.

So maybe this issue should be more: Could we please add UUID V3 or V5?

**Comment by tavurth** [comment]
Here's the `test.gd`

<details>
Godot Engine v4.2.stable.official.46dc27791 - https://godotengine.org
OpenGL API 4.1 INTEL-20.6.4 - Compatibility - Using Device: Intel Inc. - Intel(R) Iris(TM) Plus Graphics 655

Testing is_equal function
Done.
Detecting collision ...
Number of collision: 0
Collision detection done
Detecting collision with rng ...
Number of collision: 0
Collision detection done

----------------      Raw      ----------------
Benchmarking ...
uuid/sec: 100625.41   avg time: 9.9378us   total time: 4.97s
Benchmark done

---------------- Raw with rng  ----------------
Benchmarking ...
uuid/sec: 97300.40   avg time: 10.2775us   total time: 5.14s
Benchmark done

---------------- Simple object ----------------
Benchmarking ...
uuid/sec: 133530.53   avg time: 7.4889us   total time: 3.74s
Benchmark done

---------------- Obj with rng  ----------------
Benchmarking ...
uuid/sec: 146796.28   avg time: 6.8122us   total time: 3.41s
Benchmark done

----------------  Obj to dict  ----------------
Setting up benchmark ...
Benchmarking ...
uuid/sec: 369718.76   avg time: 2.7048us   total time: 0.14s
Cleaning up ...
Benchmark done

---------------- Obj to string ----------------
Setting up benchmark ...
Benchmarking ...
uuid/sec: 122283.77   avg time: 8.1777us   total time: 0.41s
Cleaning up ...
Benchmark done
</details>

This part taking a long time to run:
```
----------------  Compare raw  ----------------
Setting up benchmark ...
Benchmarking ...
```

**Comment by xsellier** [comment]
Thank you for running those tests, I appreciate frankly.
Let me do some more tests locally, then I'll make some changes.

Reworking the repo in order to be compliant with the Godot Asset requirements.

**Comment by xsellier** [comment]
Thank you for your feedback and I'm sorry for being a bit rude, I'm struggling with the Steamwork API and auth ticket validation that always returns an error code 10 for the first ticket I generate, but if I generate another one then everything seems alright... anyway

The addon hsa been updated, thank you!

**Comment by tavurth** [comment]
Thank you!
