### ISSUE TITLE
inconsistent tabs and spaces

### ISSUE THREAD

**Issue by JohnRudy** [xsellier/godot-uuid#14]
uuid.gd file uses inconsistent tabs and spaces. 

```
Line 76:Used tab character for indentation instead of space as used before in the file.
Line 84:Used tab character for indentation instead of space as used before in the file.
```

fix: 
Convert tabs to spaces
or 
Yeet `as_dict`

**Comment by xsellier** [comment]
Hey,

Sorry for the delay,
There's no tabulation in the file.
If you want to, you can copy it directly using this link:
https://raw.githubusercontent.com/binogure-studio/godot-uuid/master/addons/uuid/uuid.gd

Closing it.
Cheers

**Comment by JohnRudy** [comment]
>  There's no tabulation in the file.

Incorrect. 

Following screenshots from VSCode and Godot script editor after downloading raw uuid.gd script. 

![Screenshot from 2024-08-08 12-50-14](https://github.com/user-attachments/assets/bdd2b7e0-6f29-4664-9c80-8b50ed0eeb53)
![Screenshot from 2024-08-08 12-51-47](https://github.com/user-attachments/assets/2485f287-578b-4873-877a-7ebdf85c47fd)

Issue is not fixed. 

Fix: Switch to use tabs OR spaces.

**Comment by xsellier** [comment]
I tried either via the godot asset and via github, and on both of them there no issue.
Anyway, I commit a new version that reaplce all the tabs by 2 spaces using a regex. Sooooo...

**Comment by MageCoven** [comment]
I encountered this in version 2.1.1 of uuid with Godot 4.3. It seems like the script editor in Godot automatically converts 4 spaces into a tab on save.

**Comment by xsellier** [comment]
> I encountered this in version 2.1.1 of uuid with Godot 4.3. It seems like the script editor in Godot automatically converts 4 spaces into a tab on save.

Everything makes sense now ! thanks for the comment

**Comment by juspky** [comment]
I got the issue too when I install it in Godot 4.4 I cant use it because tabs and spaces are messed up.

Had to fix the tabs in the whole file to make it work

**Comment by xsellier** [comment]
> I got the issue too when I install it in Godot 4.4 I cant use it because tabs and spaces are messed up.
> 
> Had to fix the tabs in the whole file to make it work

It's because the Godot editor is set to use tabs instead of spaces. This addon uses spaces instead of tabs.

**Comment by juspky** [comment]
It doesnt really make sense to me why you would publish this addon with double spaces if it gives errors to 99% of the users.
Also if you use tabs you can just set the tab size to 2 (or someone can change it to their own preference) if you prefer that style.
