### ISSUE TITLE
Request for instructions

### ISSUE THREAD

**Issue by ghost** [xsellier/godot-uuid#4]
I'm trying to use the code for my own project, but I do not know which is the function needed to be called or where is the generated uuid located. Can we get a short step-by-step or shot explanation on how to use it?

**Comment by ghost** [comment]
You probably figured out, but this is the function and it returns the uuid-v4 as a `String`
https://github.com/binogure-studio/godot-uuid/blob/master/uuid.gd#L23

But I agree with some explanations 👍

**Comment by xsellier** [comment]
Thank you for the report.
It's been fixed
