### ISSUE TITLE
Can you add this to the asset library?

### ISSUE THREAD

**Issue by Enaero** [xsellier/godot-uuid#5]
Thanks for writing this utility method. Can you add this to the asset library so we don't have to copy the file into the project?

Would help simplify things like licensing, as well as easily let people get updates.

**Comment by xsellier** [comment]
Hey,

Normally it is already in the asset library:
https://godotengine.org/asset-library/asset/81

**Comment by Enaero** [comment]
Ah I see but I wasn't seeing it because I am using Godot 3+. I think the editor only shows you assets for your version.

**Comment by xsellier** [comment]
Indeed, feel free to submit a PR to make this addon Godot 3.x compatible
